# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AddField(
            model_name='device',
            name='customName',
            field=models.CharField(default='Light', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
