# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20160503_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='customName',
        ),
    ]
