# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_remove_device_customname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCustomization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
    ]
