# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeauto_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
